language: android

android:
    components:
        - tools
        - build-tools-25.0.0
        - android-25
        - platform-tools
        - extra-android-support
        - extra-android-m2repository

jdk:
    - oraclejdk8
script:
    - ./gradlew build
